[phases.setup]
nixPkgs = [
    'php82',
    'php82Extensions.gd',
    'php82Extensions.pdo',
    'php82Extensions.pdo_mysql',
    'php82Extensions.mbstring',
    'php82Extensions.intl',
    'php82Extensions.xml',
    'php82Extensions.curl',
    'php82Extensions.zip',
    'php82Extensions.bcmath',
    'php82Extensions.redis',
    'php82Extensions.tokenizer',
    'php82Extensions.ctype',
    'php82Extensions.fileinfo',
    'php82Extensions.dom',
    'php82Extensions.exif',
    'php82Extensions.pcntl',
    'php82Extensions.opcache',
    'php82Extensions.soap',
    'libpng',
    'libjpeg',
    'freetype',
    'phpPackages.composer',
    'nodejs'
]

[phases.build]
cmds = [
    'composer install --no-dev --optimize-autoloader --no-interaction',
    'npm install',
    'npm run build'
]

[start]
cmd = 'bash -c "sleep 3 && php artisan bagisto:install --skip-env-check --skip-admin-creation --skip-github-star --no-interaction || true && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan storage:link --force && php artisan serve --host=0.0.0.0 --port=$PORT"'
